const express=require("express"),path=require("path"),crypto=require("crypto"),cookieSession=require("cookie-session");require("dotenv").config();const db=require("./lib/storage");
const app=express(),PORT=process.env.PORT||3000;app.use(express.json());app.use(cookieSession({name:"fw",keys:[process.env.SESSION_SECRET||"local-dev-secret"],maxAge:2592000000,httpOnly:true,sameSite:"lax",secure:process.env.NODE_ENV==="production"}));
app.set("trust proxy", 1);
const protectedMode=Boolean(process.env.APP_PASSWORD);
app.get("/api/auth/status",(q,r)=>r.json({protected:protectedMode,authenticated:!protectedMode||!!q.session?.authenticated}));
app.post("/api/auth/login",(q,r)=>{if(!protectedMode){q.session.authenticated=true;return r.json({ok:true})}const a=Buffer.from(String(q.body?.password||"")),b=Buffer.from(String(process.env.APP_PASSWORD));if(a.length!==b.length||!crypto.timingSafeEqual(a,b))return r.status(401).json({error:"Incorrect password."});q.session.authenticated=true;r.json({ok:true})});
app.post("/api/auth/logout",(q,r)=>{q.session=null;r.json({ok:true})});
app.use("/api",(q,r,n)=>{if(q.path.startsWith("/auth/")||q.path==="/health"||!protectedMode||q.session?.authenticated)return n();r.status(401).json({error:"Authentication required."})});
async function explore(origin){const p=new URLSearchParams({engine:"google_travel_explore",departure_id:origin,gl:"us",hl:"en",currency:"USD",type:"1",api_key:process.env.SERPAPI_KEY});const res=await fetch("https://serpapi.com/search.json?"+p),d=await res.json();if(!res.ok||d.error)throw new Error(d.error||"SerpApi failed");return d}
function norm(d,o,i){return{id:`${o}-${d.destination_airport?.code||d.arrival_airport?.code||d.destination_id||i}-${d.start_date||i}`,destination:d.name||"Unknown",country:d.country||"",price:Number(d.flight_price??d.price??0),flightLink:d.link||d.flight_link||null,startDate:d.start_date||null,endDate:d.end_date||null,departureAirport:o,arrivalAirport:d.destination_airport?.code||d.arrival_airport?.code||null,flightDuration:d.flight_duration?Number(d.flight_duration):null,stops:d.number_of_stops??d.stops??null,airline:d.airline||null,hotelPrice:d.hotel_price?Number(d.hotel_price):null}}
app.get("/api/health",(q,r)=>r.json({ok:true,apiConfigured:!!process.env.SERPAPI_KEY,database:db.usePostgres?"postgres":"local"}));
app.get("/api/deals",async(q,r)=>{try{if(!process.env.SERPAPI_KEY)return r.status(500).json({error:"SERPAPI_KEY is missing."});const req=String(q.query.origin||"BOTH").toUpperCase(),origins=req==="BOTH"?["MCO","MIA"]:["MCO","MIA"].includes(req)?[req]:["MCO","MIA"];const rs=await Promise.all(origins.map(explore));let deals=[];rs.forEach((x,i)=>deals.push(...(x.destinations||x.flights||[]).map((d,j)=>norm(d,origins[i],j))));deals=deals.filter(d=>(d.country||"").trim().toLowerCase()==="united states"&&d.price>0);const u=new Map();for(const d of deals){const k=`${d.departureAirport}|${d.arrivalAirport||d.destination}|${d.startDate}|${d.endDate}`;if(!u.has(k)||d.price<u.get(k).price)u.set(k,d)}deals=[...u.values()].sort((a,b)=>a.price-b.price);await db.saveSnapshots(deals);r.json({deals,fetchedAt:new Date().toISOString(),source:"Google Travel Explore via SerpApi"})}catch(e){r.status(500).json({error:e.message})}});
app.get("/api/profile",async(q,r)=>r.json(await db.getProfile()));app.put("/api/profile",async(q,r)=>r.json(await db.saveProfile(q.body||{})));
app.get("/api/tracked",async(q,r)=>r.json(await db.getTracked()));app.post("/api/tracked",async(q,r)=>r.json(await db.addTracked(q.body||{})));app.delete("/api/tracked/:id",async(q,r)=>{await db.removeTracked(q.params.id);r.json({ok:true})});
app.get("/api/watchlists",async(q,r)=>r.json(await db.getWatchlists()));app.post("/api/watchlists",async(q,r)=>r.json(await db.addWatchlist(q.body||{})));app.delete("/api/watchlists/:id",async(q,r)=>{await db.removeWatchlist(q.params.id);r.json({ok:true})});
app.get("/api/history",async(q,r)=>r.json(await db.history(q.query.origin||"",String(q.query.destinationCode||"").toUpperCase(),q.query.limit)));
app.get("/api/status",async(q,r)=>r.json({...await db.status(),apiConfigured:!!process.env.SERPAPI_KEY,protectedMode}));
app.use(express.static(path.join(__dirname,"public")));app.get("*",(q,r)=>r.sendFile(path.join(__dirname,"public","index.html")));
db.init().then(()=>app.listen(PORT,()=>console.log(`FlightWatch V3 running at http://localhost:${PORT}`))).catch(e=>{console.error(e);process.exit(1)});
