const fs=require("fs"),path=require("path"); const {Pool}=require("pg");
const usePostgres=Boolean(process.env.DATABASE_URL); let pool=null;
const dataDir=path.join(__dirname,"..",".data"), dataFile=path.join(dataDir,"flightwatch.json");
const blank=()=>({profile:{email:"",phone:"",notifyEmail:true,notifySms:false,quietHoursEnabled:false,quietStart:"22:00",quietEnd:"08:00",maxPrice:150,nonstopOnly:false},tracked:[],watchlists:[],snapshots:[],meta:{lastFlightCheck:null}});
function ensure(){if(!fs.existsSync(dataDir))fs.mkdirSync(dataDir,{recursive:true});if(!fs.existsSync(dataFile))fs.writeFileSync(dataFile,JSON.stringify(blank(),null,2))}
function read(){ensure();try{return JSON.parse(fs.readFileSync(dataFile,"utf8"))}catch{return blank()}}
function write(d){ensure();fs.writeFileSync(dataFile,JSON.stringify(d,null,2))}
async function init(){if(!usePostgres){ensure();return} pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:{rejectUnauthorized:false}});
await pool.query(`CREATE TABLE IF NOT EXISTS profile(id int primary key,email text default '',phone text default '',notify_email boolean default true,notify_sms boolean default false,quiet_hours_enabled boolean default false,quiet_start text default '22:00',quiet_end text default '08:00',max_price numeric default 150,nonstop_only boolean default false,updated_at timestamptz default now());
INSERT INTO profile(id) VALUES(1) ON CONFLICT(id) DO NOTHING;
CREATE TABLE IF NOT EXISTS tracked(id text primary key,origin text,destination_code text,destination_name text,start_date text,end_date text,airline text,created_at timestamptz default now());
CREATE TABLE IF NOT EXISTS watchlists(id text primary key,label text,origin text,destination_code text,destination_name text,max_price numeric,nonstop_only boolean default false,enabled boolean default true,created_at timestamptz default now());
CREATE TABLE IF NOT EXISTS snapshots(id bigserial primary key,deal_key text,origin text,destination_code text,destination_name text,start_date text,end_date text,airline text,stops int,duration_minutes int,price numeric,captured_at timestamptz default now());
CREATE INDEX IF NOT EXISTS snapshots_route_idx ON snapshots(origin,destination_code,captured_at);
CREATE TABLE IF NOT EXISTS app_meta(key text primary key,value text);`)}
const pRow=r=>({email:r.email||"",phone:r.phone||"",notifyEmail:r.notify_email,notifySms:r.notify_sms,quietHoursEnabled:r.quiet_hours_enabled,quietStart:r.quiet_start,quietEnd:r.quiet_end,maxPrice:Number(r.max_price||150),nonstopOnly:r.nonstop_only});
async function getProfile(){if(!usePostgres)return read().profile;return pRow((await pool.query("select * from profile where id=1")).rows[0])}
async function saveProfile(p){const x={email:String(p.email||"").trim(),phone:String(p.phone||"").trim(),notifyEmail:!!p.notifyEmail,notifySms:!!p.notifySms,quietHoursEnabled:!!p.quietHoursEnabled,quietStart:p.quietStart||"22:00",quietEnd:p.quietEnd||"08:00",maxPrice:Math.max(1,Number(p.maxPrice||150)),nonstopOnly:!!p.nonstopOnly};if(!usePostgres){let d=read();d.profile=x;write(d);return x}const r=await pool.query(`update profile set email=$1,phone=$2,notify_email=$3,notify_sms=$4,quiet_hours_enabled=$5,quiet_start=$6,quiet_end=$7,max_price=$8,nonstop_only=$9,updated_at=now() where id=1 returning *`,[x.email,x.phone,x.notifyEmail,x.notifySms,x.quietHoursEnabled,x.quietStart,x.quietEnd,x.maxPrice,x.nonstopOnly]);return pRow(r.rows[0])}
async function getTracked(){if(!usePostgres)return read().tracked;return (await pool.query("select * from tracked order by created_at desc")).rows.map(r=>({id:r.id,departureAirport:r.origin,arrivalAirport:r.destination_code,destination:r.destination_name,startDate:r.start_date,endDate:r.end_date,airline:r.airline}))}
async function addTracked(x){const d={id:String(x.id),departureAirport:x.departureAirport||"",arrivalAirport:x.arrivalAirport||"",destination:x.destination||"",startDate:x.startDate||null,endDate:x.endDate||null,airline:x.airline||""};if(!usePostgres){let a=read();a.tracked=[d,...a.tracked.filter(v=>v.id!==d.id)];write(a);return d}await pool.query(`insert into tracked(id,origin,destination_code,destination_name,start_date,end_date,airline) values($1,$2,$3,$4,$5,$6,$7) on conflict(id) do nothing`,[d.id,d.departureAirport,d.arrivalAirport,d.destination,d.startDate,d.endDate,d.airline]);return d}
async function removeTracked(id){if(!usePostgres){let d=read();d.tracked=d.tracked.filter(x=>x.id!==id);write(d);return}await pool.query("delete from tracked where id=$1",[id])}
async function getWatchlists(){if(!usePostgres)return read().watchlists;return (await pool.query("select * from watchlists order by created_at desc")).rows.map(r=>({id:r.id,label:r.label,origin:r.origin,destinationCode:r.destination_code,destinationName:r.destination_name,maxPrice:Number(r.max_price),nonstopOnly:r.nonstop_only,enabled:r.enabled}))}
async function addWatchlist(w){const x={id:`watch-${Date.now()}-${Math.random().toString(16).slice(2)}`,label:String(w.label||"My watchlist"),origin:["MCO","MIA","BOTH"].includes(w.origin)?w.origin:"BOTH",destinationCode:String(w.destinationCode||"ANY").toUpperCase(),destinationName:String(w.destinationName||""),maxPrice:Math.max(1,Number(w.maxPrice||150)),nonstopOnly:!!w.nonstopOnly,enabled:true};if(!usePostgres){let d=read();d.watchlists.unshift(x);write(d);return x}await pool.query(`insert into watchlists(id,label,origin,destination_code,destination_name,max_price,nonstop_only,enabled) values($1,$2,$3,$4,$5,$6,$7,true)`,[x.id,x.label,x.origin,x.destinationCode,x.destinationName,x.maxPrice,x.nonstopOnly]);return x}
async function removeWatchlist(id){if(!usePostgres){let d=read();d.watchlists=d.watchlists.filter(x=>x.id!==id);write(d);return}await pool.query("delete from watchlists where id=$1",[id])}
async function saveSnapshots(deals){if(!deals.length)return;const now=new Date().toISOString();if(!usePostgres){let d=read();for(const x of deals)d.snapshots.push({origin:x.departureAirport,destinationCode:x.arrivalAirport||"",destinationName:x.destination||"",startDate:x.startDate||null,endDate:x.endDate||null,airline:x.airline||"",stops:x.stops??null,durationMinutes:x.flightDuration??null,price:Number(x.price),capturedAt:now});d.snapshots=d.snapshots.slice(-15000);d.meta.lastFlightCheck=now;write(d);return}const c=await pool.connect();try{await c.query("begin");for(const x of deals)await c.query(`insert into snapshots(deal_key,origin,destination_code,destination_name,start_date,end_date,airline,stops,duration_minutes,price) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)`,[`${x.departureAirport}|${x.arrivalAirport||x.destination}|${x.startDate||""}|${x.endDate||""}`,x.departureAirport,x.arrivalAirport||"",x.destination||"",x.startDate||null,x.endDate||null,x.airline||"",x.stops??null,x.flightDuration??null,x.price]);await c.query(`insert into app_meta(key,value) values('lastFlightCheck',$1) on conflict(key) do update set value=excluded.value`,[now]);await c.query("commit")}catch(e){await c.query("rollback");throw e}finally{c.release()}}
async function history(o,d,l=300){if(!usePostgres)return read().snapshots.filter(x=>(!o||x.origin===o)&&(!d||x.destinationCode===d)).slice(-l);return (await pool.query(`select origin,destination_code as "destinationCode",destination_name as "destinationName",start_date as "startDate",end_date as "endDate",airline,stops,duration_minutes as "durationMinutes",price,captured_at as "capturedAt" from snapshots where origin=$1 and destination_code=$2 order by captured_at asc limit $3`,[o,d,Math.min(500,Number(l)||300)])).rows.map(x=>({...x,price:Number(x.price)}))}
async function status(){if(!usePostgres){let d=read();return{database:"Local JSON",lastFlightCheck:d.meta.lastFlightCheck,snapshots:d.snapshots.length,tracked:d.tracked.length,watchlists:d.watchlists.length}}const [s,t,w,m]=await Promise.all([pool.query("select count(*)::int c from snapshots"),pool.query("select count(*)::int c from tracked"),pool.query("select count(*)::int c from watchlists"),pool.query("select value from app_meta where key='lastFlightCheck'")]);return{database:"PostgreSQL",lastFlightCheck:m.rows[0]?.value||null,snapshots:s.rows[0].c,tracked:t.rows[0].c,watchlists:w.rows[0].c}}
module.exports={init,usePostgres,getProfile,saveProfile,getTracked,addTracked,removeTracked,getWatchlists,addWatchlist,removeWatchlist,saveSnapshots,history,status};
